### PR TITLE
First pass at sprucing up Haxegon website. :)

### PR DESCRIPTION
**Pull request by Doppp**
Had some downtime this week so I decided to try my hand at making a simple website for Haxegon. I'm not a web design expert so this is a really simple design. It's mostly static content and isn't as powerful as, say, a WordPress site. You can choose to launch this with the release of 1.0 or launch it now. Definitely requires more changes in the future.

I switched to [Jekyll](https://jekyllrb.com/) because I couldn't figure out how to use `buildsite.js`. Another reason for this is that GitHub Pages are powered by Jekyll and you can also use the [`https` functionality for free](https://help.github.com/articles/securing-your-github-pages-site-with-https/). Sorry about that @TerryCavanagh! I did tweak `buildsite.js` to generate the docs, however. I'm thinking of changing the colours for the words to match the orange on the main site but this will do for now.

I used images from both @TerryCavanagh and @increpare's games for the `Showcase` section of the site. Let me know if you do not want the games and their images listed there.

I also suggest using a `gh-pages` branch for convenient GitHub Pages hosting.

Here's a screenshot:

haxegon

Test the site out and let me know your thoughts!

### CODE REVIEW

**Comment by TerryCavanagh** [comment]
Oh wow!

Not at a computer right now, but really excited to check it out later tonight!

**Comment by TerryCavanagh** [comment]
This is really great - thank you so much for all your work! (I've added you as a collaborator for the website with write permissions. Feel free to make any additions or changes that you like.)

I'm going to have a look at generating doc pages from the old node.js `buildsite.js` system soon!

I'm not that familiar with github pages, so I'm not sure how best to structure this so that changes can be previewed. I welcome any pull requests to create preview branches, or anything like that :)

**Comment by Doppp** [comment]
Thanks @TerryCavanagh! :)

Regarding GitHub Pages, what I'd recommend now is to create a `gh-pages` branch and then setting it to be your default branch.

The website can be accessed via `https://haxegon.github.io`. I think the current `haxegon.com` site is hosted by you so you would have to kill that and then go into this repository's settings. Under `GitHub Pages`, change the `Source` branch, `Custom domain` and check the `Enforce HTTPS` box. You can also rename the repository to `haxegon.com`

Try that and see if this works! :)

**Comment by Doppp** [comment]
Oh I'd also suggest not reinventing the wheel when it comes to generating documentation. We could use [Dox](https://github.com/HaxeFoundation/dox), the documentation generator for Haxe (used by the major Haxe projects) or just simply use Jekyll. For Dox, you mainly need to have [block comments](https://github.com/HaxeFoundation/dox/wiki/How-to-document-Haxe-code) for your code i.e. Javadoc style.

**Comment by TerryCavanagh** [comment]
I've updated the DNS for the domain name, so Haxegon.com is live! Alright! 

(Re: documentation, I have fairly big plans here, so I'm going to do a bit of a rewrite on the old `buildsite.js` system later this week. I'll get it to export markdown instead of html, in the new site style.)

**Comment by Doppp** [comment]
Sounds good! Oh, don't forget to print the documentation in alphabetical order too, it's not right now. :)

**Pull request merged**
